version: "3.8"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - flask_data:/image/data
    deploy:
      resources:
        limits:
          memory: 200M

volumes:
  flask_data:
    driver: local
